version: '3.8'

services:
  web:
    build: .
    image: nailsonseat/profiler-backend:profiler
    command: gunicorn --bind 0.0.0.0:8000 server.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
